package org.test.restaurant_service.dto.response;

import lombok.AccessLevel;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

@Data
@NoArgsConstructor(access = AccessLevel.PRIVATE) // Private constructor for parent class
public class StatisticsResultResponseDto {

    private LocalDateTime from;
    private LocalDateTime to;
    private List<ProductSalesResponseDto> productSalesResponseDto;
    private TotalRevenueBasedOrdersDto totalRevenueBasedOrdersDto;

    // Factory method to create an instance of the parent class
    public static StatisticsResultResponseDto create() {
        return new StatisticsResultResponseDto();
    }

    @Data
    @NoArgsConstructor(access = AccessLevel.PRIVATE) // Private constructor for inner class
    public static class ProductSalesResponseDto {

        private ProductResponseDTO productResponseDTO;
        private int totalQuantitySold;     // Total quantity of this product sold
//        private BigDecimal totalRevenue;   // Revenue generated by this product

        // Factory method to create an instance
        public static ProductSalesResponseDto create() {
            return new ProductSalesResponseDto();
        }
    }

    @Data
    @NoArgsConstructor(access = AccessLevel.PRIVATE) // Private constructor for inner class
    public static class TotalRevenueBasedOrdersDto {

        private BigDecimal totalRevenue;   // Total revenue for the date
        private int totalOrders;           // Total number of orders for the date
        private BigDecimal avgRevenuePerOrder;

        // Factory method to create an instance
        public static TotalRevenueBasedOrdersDto create() {
            return new TotalRevenueBasedOrdersDto();
        }
    }

}
