spring:
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    username: default
  application:
    name: Restaurant_Service
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000  # Таймаут для простоящих соединений (мс)
      connection-timeout: 20000 # Таймаут для подключения (мс)
      max-lifetime: 1800000 # Максимальное время жизни соединения (мс)
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        connection:
          release_mode: after_transaction
        show_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
        jdbc:
          batch_size: 20
          batch_versioned_data: true
        order_updates: ${SPRING_JPA_PROPERTIES_HIBERNATE_ORDER_UPDATES}
        generate_statistics: ${SPRING_JPA_PROPERTIES_HIBERNATE_GENERATE_STATISTICS}
        format_sql: true
    open-in-view: false


  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    schemas: ${SPRING_FLYWAY_SCHEMAS}
    clean-disabled: false
    out-of-order: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

rabbitmq:
  queues:
    json:
      queue1:
        name: order_saving_queue
        routingKey: ${RABBITMQ_QUEUES_JSON_QUEUE1_ROUTINGKEY}
      queue2:
        name: product_history_saving_queue
        routingKey: ${RABBITMQ_QUEUES_JSON_QUEUE2_ROUTINGKEY}
      queue3:
        name: order_bulk_from_admin_queue
        routingKey: ${RABBITMQ_QUEUES_JSON_QUEUE3_ROUTINGKEY}
  exchanges:
    exchange:
      name: java_exchange

server:
  port: ${SERVER_PORT}

jwt:
  access: ${JWT_ACCESS}

telegram:
  bot:
    name:
      ${BOT_NAME}
    key:
      ${BOT_KEY}
  workBot:
    name:
      ${WORK_BOT_NAME}
    key:
      ${WORK_BOT_KEY}


scheduler:
  cron:
    0 0 12 * * ?
  enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

aws:
  java:
    v1:
      disableDeprecationAnnouncement: true
  accessKey: ${AWS_ACCESS_KEY}
  secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
  bucketName: ${AWS_BUCKET_NAME}


admin:
  code1: ${ADMIN_CODE1}
  code2: ${ADMIN_CODE2}

disposable:
  adminKey: ${DISPOSABLE_ADMIN_KEY}
#logging:
#  level:
#    org:
#      test:
#        restaurant_service:
#          controller:
#            websocket: debug
#          service:
#            PrinterService: debug
#            impl:
#              OrderServiceImpl: debug
#    org.test.restaurant_service.service.impl.SendingUsersServiceImpl: debug
#    org.test.restaurant_service.telegram: debug