spring:
  application:
    name: Restaurant_Service
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    show-sql: ${SPRING_JPA_SHOW_SQL}
    properties:
      hibernate:
        show_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_SHOW_SQL}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED}
    locations: ${SPRING_FLYWAY_LOCATIONS}
    baseline-on-migrate: ${SPRING_FLYWAY_BASELINE_ON_MIGRATE}
    schemas: ${SPRING_FLYWAY_SCHEMAS}
    clean-disabled: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

rabbitmq:
  queues:
    json:
      queue:
        name: restaurant_json
        routingKey: restaurant_routing_key_secret
  exchanges:
    exchange:
      name: java_exchange


server:
  port: ${SERVER_PORT}

jwt:
  access: ${JWT_ACCESS}

#logging:
#  level:
#    # Логирование WebSocket
#    org.springframework.web.socket: DEBUG
#    org.springframework.messaging: DEBUG
#    org.springframework.web.socket.messaging: DEBUG
#    # Логирование ошибок Tomcat (если используется встроенный Tomcat)
#    org.springframework.boot.web.embedded.tomcat: DEBUG

bot:
  name:
    ${BOT_NAME}
  key:
    ${BOT_KEY}

cron:
  scheduler: 0 * * * * *

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus

  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true