-- todo table for receive user of or on send in tg
CREATE TABLE IF NOT EXISTS restaurant_service.staff_sending_order
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid  uuid REFERENCES restaurant_service.users (uuid) NOT NULL UNIQUE,
    chat_id    BIGINT UNIQUE                                   NOT NULL,
    sending_on boolean DEFAULT false                           NOT NULL,
    UNIQUE (user_uuid, sending_on)
);
