CREATE TABLE IF NOT EXISTS restaurant_service.product_i18n
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    product_id  INTEGER REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    lang_id     INTEGER REFERENCES restaurant_service.language (id) ON DELETE CASCADE,
    name        VARCHAR(128) NOT NULL,
    description VARCHAR(128),
    PRIMARY KEY (id, lang_id)
);


