CREATE TABLE IF NOT EXISTS restaurant_service.product_type_translations
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_type_id INTEGER      NOT NULL REFERENCES restaurant_service.product_types (id) ON DELETE CASCADE,
    lang_id         INTEGER REFERENCES restaurant_service.language (id) ON DELETE CASCADE,
    name            VARCHAR(128) NOT NULL,
    UNIQUE (product_type_id, lang_id)
);


