CREATE TABLE IF NOT EXISTS restaurant_service.discounts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)   NOT NULL UNIQUE,                                   -- Промокод
    description TEXT,
    discount    DECIMAL(5, 2) NOT NULL CHECK (discount > 0 AND discount <= 100), -- Скидка в процентах
    valid_from  TIMESTAMP     NOT NULL,
    valid_to    TIMESTAMP     NOT NULL
);
