CREATE TABLE IF NOT EXISTS restaurant_service.ui_translations
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key     TEXT NOT NULL,
    lang_id INTEGER REFERENCES restaurant_service.language (id) ON DELETE CASCADE,
    value   TEXT NOT NULL,
    UNIQUE (key, lang_id)
);
