CREATE TABLE IF NOT EXISTS restaurant_service.product_history
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   INTEGER REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    name         TEXT           NOT NULL,
    description  TEXT,
    type_id      INTEGER REFERENCES restaurant_service.product_types (id),
    price        DECIMAL(10, 2) NOT NULL,
    cooking_time TIME,
    changed_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);
