-- Создаем таблицу sessions
CREATE TABLE IF NOT EXISTS restaurant_service.otp_tg_codes
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    otp_code   VARCHAR(6) UNIQUE,
    chat_id    BIGINT UNIQUE,
    username   VARCHAR(256) NOT NULL,
    firstname  VARCHAR(256) NOT NULL,
    verified   BOOLEAN   DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (chat_id, otp_code)
);
