-- Создаем таблицу sessions
CREATE TABLE IF NOT EXISTS restaurant_service.telegram_user
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    BIGINT UNIQUE NOT NULL,
    username   VARCHAR(256)  NOT NULL,
    firstname  VARCHAR(256)  NOT NULL,
    photo_url  VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
