CREATE TABLE IF NOT EXISTS restaurant_service.users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    otp_id     INTEGER REFERENCES restaurant_service.otp_tg_codes (id) UNIQUE
);

