CREATE TABLE IF NOT EXISTS restaurant_service.roles
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);
INSERT INTO restaurant_service.roles
    (name)
VALUES ('ROLE_USER'),
       ('ROLE_ADMIN');
