CREATE TABLE IF NOT EXISTS restaurant_service.address
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city             VARCHAR(64),
    street           VARCHAR(128),
    home_number      VARCHAR(128),
    apartment_number VARCHAR(8),
    user_uuid        uuid REFERENCES restaurant_service.users (uuid) ON DELETE CASCADE UNIQUE
);

