CREATE TABLE IF NOT EXISTS restaurant_service.orders
(
    id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_id       INTEGER REFERENCES restaurant_service.tables (id),
    user_uuid      uuid REFERENCES restaurant_service.users (uuid),
    address_id     INTEGER REFERENCES restaurant_service.address (id),
    status         TEXT      NOT NULL CHECK (status IN ('PENDING', 'CONFIRMED', 'COMPLETED')),
    payment_method VARCHAR(50) CHECK (payment_method IN ('CASH', 'CARD')),
    total_price    DECIMAL(10, 2),
    created_at     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP          DEFAULT CURRENT_TIMESTAMP
);

-- Индексы
CREATE INDEX idx_orders_status ON restaurant_service.orders (status);
CREATE INDEX idx_orders_created_at ON restaurant_service.orders (created_at);
CREATE INDEX idx_orders_table_id ON restaurant_service.orders (table_id);

