-- Таблица для позиций в заказах
CREATE TABLE restaurant_service.order_products
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   INTEGER REFERENCES restaurant_service.orders (id) ON DELETE CASCADE,
    product_id INTEGER REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    quantity   INT NOT NULL,
    CONSTRAINT unique_order_item UNIQUE (order_id, product_id)
);



