CREATE TABLE IF NOT EXISTS restaurant_service.order_discounts
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER REFERENCES restaurant_service.orders (id) ON DELETE CASCADE,
    discount_id INTEGER REFERENCES restaurant_service.discounts (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_discounts_order_id ON restaurant_service.order_discounts (order_id);
