CREATE TABLE IF NOT EXISTS restaurant_service.order_discount
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    INTEGER REFERENCES restaurant_service.orders (id)    NOT NULL UNIQUE,
    discount_id INTEGER REFERENCES restaurant_service.discounts (id) NOT NULL,
    created_at  TIMESTAMP                                            NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_id, discount_id)
);
