CREATE TABLE IF NOT EXISTS restaurant_service.otp_code
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid  uuid REFERENCES restaurant_service.users (uuid) NOT NULL,
    otp_code   VARCHAR(10)                                     NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP             NOT NULL,
    expires_at TIMESTAMP                                       NOT NULL,
    is_used    BOOLEAN   DEFAULT FALSE
);
