CREATE TABLE IF NOT EXISTS restaurant_service.photo
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    url        VARCHAR(256) NOT NULL,
    UNIQUE (product_id, url)
);
INSERT INTO restaurant_service.photo (product_id, url)
VALUES (1, '/static/images/cola.jpeg'),
       (2, '/static/images/tea.jpeg'),
       (3, '/static/images/soup.jpeg'),
       (4, '/static/images/cake.jpeg'),
       (5, '/static/images/caesar_salad.jpeg'),
       (6, '/static/images/steak.jpeg');