CREATE TABLE IF NOT EXISTS restaurant_service.photo
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id INTEGER REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    url        VARCHAR(256) NOT NULL,
    UNIQUE (product_id, url)
);
