CREATE TABLE IF NOT EXISTS restaurant_service.product_translations
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    INTEGER    NOT NULL REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    language_code VARCHAR(5) NOT NULL,
    name          TEXT       NOT NULL,
    description   TEXT,
    UNIQUE (product_id, language_code)
);
