CREATE TABLE IF NOT EXISTS restaurant_service.shared_bucket_products
(
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id       INTEGER NOT NULL REFERENCES restaurant_service.products (id),
    quantity         INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
    shared_bucket_id INTEGER NOT NULL REFERENCES restaurant_service.shared_bucket (id),
    user_uuid        UUID references restaurant_service.users (uuid),
    UNIQUE (shared_bucket_id, product_id, user_uuid)
);

CREATE INDEX IF NOT EXISTS idx_sbp_user_uuid ON restaurant_service.shared_bucket_products (user_uuid);


