CREATE TABLE IF NOT EXISTS restaurant_service.admins
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_uuid  uuid REFERENCES restaurant_service.users (uuid) ON DELETE CASCADE UNIQUE,
    login      VARCHAR(64)  NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);
