
CREATE TABLE IF NOT EXISTS restaurant_service.product_ingredients
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    INTEGER REFERENCES restaurant_service.products (id) ON DELETE CASCADE,
    ingredient_id INTEGER REFERENCES restaurant_service.ingredients (id) ON DELETE CASCADE,
    quantity      DECIMAL(10, 2) NOT NULL
);

CREATE INDEX idx_product_ingredients_product_id ON restaurant_service.product_ingredients (product_id);
