name: Java CI/CD with Dockerfile

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment: Main  

    steps:
    # Шаг 1: Клонируем репозиторий
    - uses: actions/checkout@v4

    # Шаг 2: Логинимся в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Шаг 3: Собираем Docker-образ и пушим в Docker Hub
    - name: Build and push Docker image
      run: |
        docker build -t default666/restaurant .
        docker push default666/restaurant
